apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant-cert
  namespace: home-assistant
spec:
  secretName: home-assistant-cert
  commonName: home-assistant.home.saltrelli.com
  dnsNames:
    - home-assistant.home.saltrelli.com
  subject:
    organizations:
      - "Home"
    organizationalUnits:
      - "IT"
  issuerRef:
    name: acme-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    size: 4096