apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant
  namespace: home-assistant
data:
  configuration.yaml: |
    homeassistant:
      auth_providers:
        - type: homeassistant
        - type: trusted_networks
          trusted_networks:
            - 10.11.12.0/23
    external_url: https://home-assistant.home.saltrelli.com
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.1.226.0/24