apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant
  namespace: home-assistant
data:
  configuration.yaml: |
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.1.226.0/24